name: Go

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5

      - name: Set up Go 1.26
        uses: actions/setup-go@v6
        with:
          go-version: 1.26

      - name: Get dependencies
        run: go mod download

      - name: golangci-lint
        run: go tool golangci-lint run

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5

      - name: Set up Go 1.26
        uses: actions/setup-go@v6
        with:
          go-version: 1.26

      - name: Get dependencies
        run: go mod download

      - name: Unit tests
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...
